version: '2'
volumes:
  pgdata:
    driver: local
  solrdata:
    driver: local
  virtuanenvs:
    driver: local
networks:
  front:
    driver: bridge
  back:
    driver: bridge
services:
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgres/data
    networks:
      - back
    env_file: secrets.env
  solr:
    image: solr
    volumes:
      - solrdata:/var/lib/solr/data
    networks:
      - back
  rabbitmq:
    image: rabbitmq
    env_file: secrets.env
  worker:
    build: .
    restart: always
    command: celery -A edd worker -l info
    links:
      - postgres
      - rabbitmq
    env_file: secrets.env
    environment:
      - C_FORCE_ROOT=true
  edd:
    build: .
    restart: always
    command: gunicorn -w 4 -b 0.0.0.0:8000 edd.wsgi:application
    links:
      - postgres
      - solr
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
