version: '2'
volumes:
  pgdata: {}
  solrdata: {}
  attachdata: {}
  staticdata: {}
  redisdata: {}
services:
  postgres:
    image: postgres:9.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file: secrets.env
  redis:
    image: redis:3.2
    volumes:
      - redisdata:/data
    expose:
      - "6379"
    command: redis-server --appendonly yes
  solr:
    image: solr:5.5
    command: /code/docker_services/solr/init_solr.sh
    volumes:
      - solrdata:/opt/solr/server/solr
      - "${EDD_HOST_DIR}.:/code/"
    expose:
      - "8983"
  edd:
    build: .
    command: /code/docker_services/init_entrypoint.sh
    env_file: secrets.env
    environment:
      SEARCH_URL: "solr://solr:8983/solr/"
      EDD_DEBUG: "false"
    depends_on:
      - postgres
      - redis
      - solr
    links:
      - postgres
      - redis
      - solr
    volumes:
      - attachdata:/var/www/uploads
      - staticdata:/var/www/static
      - "${EDD_HOST_DIR}.:/code/"
