version: '2'
volumes:
  pgdata:
    external:  # change name below to swap out alternate volumes
      name: pgdata
  solrdata:
    external:  # change name below to swap out alternate volumes
      name: solrdata
  attachdata:
    external:  # change name below to swap out alternate volumes
      name: attachdata
  staticdata:
    external:  # change name below to swap out alternate volumes
      name: staticdata
  redisdata:
    external:  # change name below to swap out alternate volumes
      name: redisdata
services:
  postgres:
    image: postgres:9.4
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file: secrets.env
  redis:
    image: redis:3.2
    restart: always
    volumes:
      - redisdata:/data
    expose:
      - "6379"
    command: redis-server --appendonly yes
  solr:
    image: solr:5.5
    restart: always
    volumes:
      - solrdata:/opt/solr/server/solr
    expose:
      - "8983"
  rabbitmq:
    image: rabbitmq:3.6-management
    restart: always
    hostname: rabbitmq
    env_file: secrets.env
    environment:
      HOSTNAME: rabbitmq
      RABBITMQ_DEFAULT_USER: edd_user
      RABBITMQ_DEFAULT_VHOST: edd
      RABBITMQ_NODENAME: rabbit@rabbitmq
    expose:
      - "5672"
      - "15672"
  flower:
    build: ./docker_services/flower/
    restart: always
    env_file: secrets.env
    environment:
      AMQP_ADMIN_HOST: rabbitmq
      AMQP_ADMIN_USERNAME: edd_user
      AMQP_HOST: rabbitmq
      AMQP_USERNAME: edd_user
      FLOWER_URL_PREFIX: flower
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    expose:
      - "5555"
  smtp:
    image: namshi/smtp
    restart: always
    expose:
      - "25"
  edd:
    build: .
    command: "true"
    env_file: secrets.env
    environment:
      SEARCH_URL: "solr://solr:8983/solr/"
      EDD_DEBUG: "false"
    volumes:
      - /usr/local/edd/:/code/
  worker:
    extends:
      service: edd
    restart: always
    command: celery -A edd worker -l info
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - smtp
      - solr
    links:
      - postgres
      - rabbitmq
      - smtp
      - solr
    environment:
      - C_FORCE_ROOT=true
    volumes:
      - attachdata:/var/www/uploads
  appserver:
    extends:
      service: edd
    restart: always
    command: ./docker_services/appserver_entrypoint.sh
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - smtp
      - solr
    links:
      - postgres
      - rabbitmq
      - redis
      - smtp
      - solr
    volumes:
      - attachdata:/var/www/uploads
      - staticdata:/var/www/static
    expose:
      - "8000"
  nginx:
    image: nginx:1.11
    restart: always
    links:
      - appserver
      - flower
      - rabbitmq
      - solr
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - appserver
    volumes:
      - /etc/ssl/edd/:/etc/ssl/edd/
    command: /code/docker_services/nginx/nginx_entrypoint.sh
