# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-21 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_default-sbml-template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='contact_extra',
            field=models.TextField(blank=True,
                                   help_text='Additional field for contact information about this '
                                             'study (e.g. contact is not a User of EDD).',
                                   null=True, verbose_name='Contact (extra)'),
        ),
    ]
