---
version: '2.1'
networks:
  proxynet: {}
  backnet: {}
volumes:
  pgdata: {}
  solrdata: {}
  attachdata: {}
  staticdata: {}
  redisdata: {}
  tlsdata: {}
services:
  postgres:
    image: postgres:9.6
    restart: always
    networks:
      - backnet
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/healthcheck.sh:/healthcheck.sh
    healthcheck:
      test: ['CMD', '/healthcheck.sh']
      interval: 1m
      timeout: 5s
      retries: 3
    expose:
      - '5432'
    env_file: secrets.env
  redis:
    image: redis:3.2
    restart: always
    networks:
      - backnet
    volumes:
      - redisdata:/data
      - ./redis/healthcheck.sh:/healthcheck.sh
    healthcheck:
      test: ['CMD', '/healthcheck.sh']
      interval: 1m
      timeout: 5s
      retries: 3
    expose:
      - '6379'
    command: redis-server --appendonly yes
  solr:
    build: ./solr/
    image: solr:5.5-edd
    restart: always
    networks:
      - backnet
    volumes:
      - solrdata:/opt/solr/server/solr
    # the built Solr image has a default healthcheck; can override interval etc.
    healthcheck:
      interval: 1m
      timeout: 15s
      retries: 3
    expose:
      - '8983'
  rabbitmq:
    image: rabbitmq:3.6-management
    restart: always
    hostname: rabbitmq
    env_file: secrets.env
    environment:
      HOSTNAME: rabbitmq
      RABBITMQ_DEFAULT_USER: edd_user
      RABBITMQ_DEFAULT_VHOST: edd
      RABBITMQ_NODENAME: rabbit@rabbitmq
    expose:
      - '5672'
      - '15672'
    networks:
      - backnet
    volumes:
      - ./rabbitmq/healthcheck.sh:/healthcheck.sh
    healthcheck:
      test: ['CMD', '/healthcheck.sh']
      interval: 1m
      timeout: 5s
      retries: 3
  flower:
    build: ./flower/
    image: flower:0.9-edd
    restart: always
    env_file: secrets.env
    environment:
      AMQP_ADMIN_HOST: rabbitmq
      AMQP_ADMIN_USERNAME: edd_user
      AMQP_HOST: rabbitmq
      AMQP_USERNAME: edd_user
      FLOWER_URL_PREFIX: flower
    networks:
      - backnet
      - proxynet
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    expose:
      - '5555'
    healthcheck:
      test: ['CMD', '/opt/celery-flower/healthcheck.sh']
      interval: 1m
      timeout: 5s
      retries: 3
  smtp:
    build: ./smtp/
    image: exim4:1.0-edd
    restart: always
    networks:
      - backnet
    expose:
      - '25'
    healthcheck:
      test: ['CMD', '/bin/healthcheck.sh', 'appserver']
      interval: 1m
      timeout: 1s
      retries: 3
  edd:
    build: ./edd/
    image: edd-core:latest
    restart: always
    command: ['application']
    env_file: secrets.env
    environment:
      EDD_DEBUG: "false"
      SEARCH_URL: "solr://solr:8983/solr/"
      VIRTUAL_HOST: "wcmorrell-mr.dhcp.lbl.gov"
      VIRTUAL_NETWORK: "edd_proxynet"
      VIRTUAL_PORT: "8000"
      VIRTUAL_STATIC: "true"
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - solr
    links:
      - postgres
      - rabbitmq
      - redis
      - smtp
      - solr
    expose:
      - '8000'
    networks:
      - backnet
      - proxynet
    volumes:
      - attachdata:/var/www/uploads
      - staticdata:/var/www/static
    healthcheck:
      test: ['CMD', 'curl', '--fail', '-LSs', 'http://localhost:8000/health/']
      interval: 1m
      timeout: 5s
      retries: 3
  worker:
    build: ./edd/
    image: edd-core:latest
    env_file: secrets.env
    environment:
      C_FORCE_ROOT: "true"
      EDD_DEBUG: "false"
      SEARCH_URL: "solr://solr:8983/solr/"
    networks:
      - backnet
    volumes:
      - attachdata:/var/www/uploads
      - staticdata:/var/www/static
    restart: always
    command: [-A, -w, edd, -p, '8000', worker]
    depends_on:
      - edd
      - postgres
      - rabbitmq
      - redis
      - solr
    links:
      - edd
      - postgres
      - rabbitmq
      - redis
      - smtp
      - solr
    healthcheck:
      test: ['CMD', 'celery', 'inspect', 'ping', '-A', 'edd', '--workdir', '/code']
      interval: 1m
      timeout: 5s
      retries: 3
  nginx:
    image: nginx:1.11
    container_name: nginx
    restart: always
    depends_on:
      - edd
      - flower
      - rabbitmq
      - solr
    links:
      - edd
      - flower
      - rabbitmq
      - solr
    networks:
      - proxynet
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /etc/usr/share/nginx/html
      - tlsdata:/etc/nginx/certs:ro
      - attachdata:/usr/share/nginx/html/uploads:ro
      - staticdata:/usr/share/nginx/html/static:ro
    # TODO: once Let's Encrypt used to init certificates, remove -k option to curl
    # TODO: add dedicated /health location in nginx config instead of reading file
    healthcheck:
      test: ['CMD', 'curl', '--fail', '-kLSs', 'https://localhost/static/500.html']
      interval: 1m
      timeout: 5s
      retries: 3
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    entrypoint:
      - '/usr/local/bin/docker-gen'
      - '-watch'
      - '-notify-sighup'
      - 'nginx'
      - '/etc/docker-gen/templates/nginx.tmpl'
      - '/etc/nginx/conf.d/default.conf'
    networks:
      - proxynet
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
